# Generated by Django 4.2.24 on 2026-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to use product's net price", max_digits=10, null=True),
        ),
    ]
