# Generated by Django 4.2.24 on 2026-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_purchase_currency_purchase_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('reseller', 'Reseller'), ('direct', 'Direct')], default='', max_length=255, null=True),
        ),
    ]
