# Generated by Django 4.2.24 on 2026-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
