# Generated by Django 4.2.24 on 2026-04-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='client',
        ),
    ]
