# Generated by Django 4.2.24 on 2026-05-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_team_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lead',
        ),
    ]
