# Generated by Django 4.2.24 on 2026-05-07 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_project_client_remove_project_lead'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_project ADD COLUMN IF NOT EXISTS priority varchar(20) NULL DEFAULT '';",
            reverse_sql="ALTER TABLE core_project DROP COLUMN IF EXISTS priority;",
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='priority',
                    field=models.CharField(blank=True, choices=[('', '---------'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='', max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('any', 'Any')], default='any', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
