# Generated by Django 4.2.24 on 2026-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_priority_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_project ADD COLUMN IF NOT EXISTS end_date date NULL;",
            reverse_sql="ALTER TABLE core_project DROP COLUMN IF EXISTS end_date;",
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='end_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_project ADD COLUMN IF NOT EXISTS start_date date NULL;",
            reverse_sql="ALTER TABLE core_project DROP COLUMN IF EXISTS start_date;",
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='start_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
        ),
    ]
