# Generated by Django 4.2.24 on 2026-07-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
