# Generated by Django 4.2.24 on 2026-07-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productfile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.product'),
        ),
    ]
