# Generated by Django 4.2.24 on 2026-07-06 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0012_alter_purchase_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='EUR', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('value_proposition', 'Value Proposition'), ('proposal_price_quote', 'Proposal / Price Quote'), ('negotiation_review', 'Negotiation / Review'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=50)),
                ('probability', models.DecimalField(blank=True, decimal_places=2, help_text='Probability in %', max_digits=5, null=True)),
                ('next_step', models.TextField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('existing_business', 'Existing Business'), ('new_business', 'New Business')], max_length=50, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('web', 'Web'), ('phone', 'Phone'), ('email', 'Email'), ('cold_call', 'Cold Call'), ('existing_customer', 'Existing Customer'), ('partner', 'Partner'), ('trade_show', 'Trade Show'), ('other', 'Other')], max_length=50, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('forecast_category', models.CharField(blank=True, choices=[('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('omitted', 'Omitted'), ('closed', 'Closed')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='client.client')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_comments', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='opportunity.opportunity')),
            ],
        ),
    ]
