# Generated by Django 4.2.24 on 2026-09-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead_title'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='lead_source',
            new_name='lead_source_choices',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
    ]
