# Generated by Django 4.2.24 on 2026-09-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacts_notes_project_end_date_project_start_date'),
        ('opportunity', '0002_rename_lead_source_opportunity_lead_source_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='next_step',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
