# Generated by Django 4.2.24 on 2026-10-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunity_teams_alter_opportunity_next_step'),
        ('task', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_opportunity', to='opportunity.opportunity'),
        ),
    ]
