# Generated by Django 4.2.24 on 2026-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_first_name_alter_lead_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status_sale',
            field=models.CharField(blank=True, choices=[('reseller', 'Reseller'), ('direct', 'Direct')], default='', max_length=255, null=True),
        ),
    ]
